package com.lm.ws.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-14T14:39:05.851+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://server.cxf.ws.lm.com/", name = "WeatherInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://server.cxf.ws.lm.com/", className = "com.lm.ws.cxf.client.QueryWeather")
    @WebMethod
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://server.cxf.ws.lm.com/", className = "com.lm.ws.cxf.client.QueryWeatherResponse")
    public java.lang.String queryWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
